language: python
dist: xenial
services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env:
        - TOXENV=py37
        - NOCONTAINER=1
        - PG_VER=9.4
      addons:
        postgresql: 9.4
    - python: 3.7
      env:
        - TOXENV=py37
        - NOCONTAINER=1
        - PG_VER=9.5
      addons:
        postgresql: 9.5
    - python: 3.7
      env:
        - TOXENV=py37
        - NOCONTAINER=1
        - PG_VER=9.7
      addons:
        postgresql: 9.7
    - python: 3.7
      env:
        - TOXENV=py37
        - NOCONTAINER=1
        - PG_VER=10
      addons:
        postgresql: 10
    - python: 3.7
      env:
        - TOXENV=py37
        - NOCONTAINER=1
        - PG_VER=11
      addons:
        postgresql: 11
    - python: 3.7
      env: TOXENV=pep8
    - python: 3.7
      env: TOXENV=docs

install:
  - pip install virtualenv wheel
  - pip install -U pip
  - python -m virtualenv ~/.venv
  - source ~/.venv/bin/activate
  - pip install tox codecov


script:
  - source ~/.venv/bin/activate
  - .travis/run_tests.sh

after_success:
  - ./.travis/upload_coverage.sh

after_script:
  - cat .tox/$TOXENV/log/$TOXENV-*.log
