version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - '127.0.0.1:5440:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - postgres
      - -c
      - log_min_duration_statement=0
      - -c
      - log_connections=on
      - -c
      - log_disconnections=on
